import type { Metadata } from 'next'
import { Krub } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'
import '@fortawesome/fontawesome-svg-core/styles.css'

const krub = Krub({
  subsets: ['thai'],
  weight: '400',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${krub.className}`}>
        <div className="flex h-screen flex-col">
          <div className="flex-1 flex flex-col">
            <Navbar />
            <div className="min-h-0 flex-1">{children}</div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
